server:
    error:
        include-stacktrace: on_param

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/Anime?createDatabaseIfNotExist=true
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: update
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG